table accidentes
	lineageTag: 9662bdfb-7d5f-4fa5-8478-fb6ba36a7494

	measure total_eventos = COUNTROWS(accidentes)
		formatString: #,0
		lineageTag: 32019660-c219-48fe-9122-7b1ebe53c17d

	measure total_heridos = SUM(accidentes[Heridos])
		formatString: #,0
		lineageTag: 5feebb79-c647-46f0-b1a2-32ea2458ed74

	measure total_muertes = SUM(accidentes[Muertos])
		formatString: #,0
		lineageTag: 336d86d6-a2cd-47cd-8476-2fff5b23cf3f

	measure accidentes_mas_tres_victimas_total =
			
			CALCULATE(
			    COUNTROWS(accidentes),
			    FILTER(accidentes, accidentes[Muertos] > 3)
			)
		formatString: 0
		lineageTag: cb612aae-90ce-4e85-bd7a-ace007ea9622

	measure accidentes_mas_tres_victimas_porcentaje =
			
			DIVIDE(
			    [accidentes_mas_tres_victimas_total],
			    [total_eventos],
			    0
			)
		lineageTag: a077ac4d-4bb6-4a16-a09a-0cc6469074c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure porcentaje_eventos =
			
			DIVIDE(
			    [total_eventos],
			    CALCULATE([total_eventos], ALL(accidentes)),
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8318f341-0c20-455a-a6a2-92548aa96bf7

	column id
		dataType: int64
		formatString: 0
		lineageTag: b1faab78-dbb0-4444-a565-0b1b40939962
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: b838c484-349f-458e-be7d-55d50ebcef1e
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 6b8ae457-7a86-4052-8bdd-b2183c2c1673
			defaultHierarchy: LocalDateTable_4e693788-ca7b-4254-a8c1-932659c00430.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column hora
		dataType: dateTime
		formatString: hh:nn
		lineageTag: 16f6438c-5633-468e-bbbf-34ac54a0d9cc
		summarizeBy: none
		sourceColumn: hora

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column uf
		dataType: string
		lineageTag: c942a703-a3e3-4df5-99f2-63c9bd105dd5
		summarizeBy: none
		sourceColumn: uf

		annotation SummarizationSetBy = Automatic

	column causa_accidente
		dataType: string
		lineageTag: d1df044f-e767-45c9-abe4-4f963f8d8dd2
		summarizeBy: none
		sourceColumn: causa_accidente

		annotation SummarizationSetBy = Automatic

	column clasificación_accidente
		dataType: string
		lineageTag: 75a0276c-b6aa-4240-8e63-e7b4205d63fb
		summarizeBy: none
		sourceColumn: clasificación_accidente

		annotation SummarizationSetBy = Automatic

	column tipo_pista
		dataType: string
		lineageTag: 3465928f-55ce-4eb1-b335-91a8b61cd876
		summarizeBy: none
		sourceColumn: tipo_pista

		annotation SummarizationSetBy = Automatic

	column Muertos
		dataType: int64
		formatString: 0
		lineageTag: 22a38479-cf94-42a0-9bbf-5daf32e376cd
		summarizeBy: sum
		sourceColumn: Muertos

		annotation SummarizationSetBy = Automatic

	column Heridos
		dataType: int64
		formatString: 0
		lineageTag: 0ea70d69-a1f7-4ffe-b289-0324254a64f8
		summarizeBy: sum
		sourceColumn: Heridos

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: 64acfd13-b28c-4ae7-842d-4b5e8b3a74ff
		dataCategory: Latitude
		summarizeBy: sum
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: aad0eca4-c0cd-414e-ba68-b0ef8552c8cb
		dataCategory: Longitude
		summarizeBy: sum
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dia_semana = FORMAT(accidentes[Fecha], "ddd")
		lineageTag: a18e3b6d-9887-46d1-9739-43760e61ac23
		summarizeBy: none
		sortByColumn: numero_dia_semana

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column numero_dia_semana = WEEKDAY(accidentes[Fecha])
		formatString: 0
		lineageTag: 8ddd2efa-b0c5-4f3a-be5f-ce37f707d350
		summarizeBy: sum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column numero_mes = MONTH(accidentes[Fecha])
		formatString: 0
		lineageTag: f972c5b0-a2ed-4171-a0db-01ea973f6949
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column mes = FORMAT(accidentes[Fecha], "mmm")
		lineageTag: aafc745d-ad1b-4ba0-becc-d2e1001776cf
		summarizeBy: none
		sortByColumn: numero_mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition accidentes = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Ambar\source\dashboard-accidentes-carreteras\data\raw\BD-Accidentes-Carreteras.xlsx"), null, true),
				    registro_acidente_Sheet = Origen{[Item="registro_acidente",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(registro_acidente_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"id", Int64.Type}, {"Fecha", type date}, {"hora", type datetime}, {"uf", type text}, {"municipio", type text}, {"causa_accidente", type text}, {"tipo_acidente", type text}, {"clasificación_accidente", type text}, {"sentido_via", type text}, {"tipo_pista", type text}, {"Personas", Int64.Type}, {"Muertos", Int64.Type}, {"Herido_Leves", Int64.Type}, {"Heridos_graves", Int64.Type}, {"ilesos", Int64.Type}, {"ignorados", Int64.Type}, {"Heridos", Int64.Type}, {"vehículos", Int64.Type}, {"latitude", type number}, {"longitude", type number}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"municipio", "tipo_acidente", "sentido_via", "Herido_Leves", "Heridos_graves", "ilesos", "ignorados", "vehículos", "Personas"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

